IF NOT EXISTS(select * from sys.tables where name = 'TB_PLANTAS')
BEGIN
	CREATE TABLE TB_PLANTAS
	(
		 Id INT PRIMARY KEY IDENTITY(1,1) 
		,Nome VARCHAR(200) NOT NULL
		,Preco MONEY NOT NULL
		,Qtd INT NOT NULL
		,Especial BIT NOT NULL
	)
END
GO


--ALTERAÇÕES--

ALTER TABLE TB_PLANTAS
ADD Status BIT NOT NULL DEFAULT(1)